Repository PerfectWeek/web-app, pull requests merged in 2019-05, with the labels that each got.

#35 Layout Revamp: Bug correction
  src/app/module/dialog/Add-member/add-member.html
  src/app/module/dialog/Friend-Invitation/invitation.html
  src/app/module/dialog/Friend-Invitation/invitation.ts
Labels: bug

#38 Changed Auth client_id for Facebook and Google
  src/app/pages/Connection/connection.ts
  src/app/pages/Registration/registration.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: bug

#39 Facebook client_id
  src/index.html
Labels: bug

#37 Feature/event suggestions
  src/app/app-routing-module.ts
  src/app/app.module.ts
  src/app/module/Navbar/navbar.html
  src/app/pages/EventSuggestions/event_suggestions.html
  src/app/pages/EventSuggestions/event_suggestions.scss
  src/app/pages/EventSuggestions/event_suggestions.ts
  src/app/pages/Main_View/main_view.html
  src/app/pages/calendar/calendar.html
  src/app/pages/calendar/calendar.ts
  src/assets/Pictures/clock-circular-outline.svg
  src/assets/Pictures/maps-and-flags.svg
  src/scss/variables.scss
Labels: enhancement

#41 Calendar & Typo
  src/app/pages/EventSuggestions/event_suggestions.ts
Labels: bug

#42 Typo correction
  src/app/app.module.ts
  src/app/core/services/auth.service.ts
  src/app/module/Navbar/navbar.html
  src/app/module/Navbar/navbar.scss
  src/app/module/Navbar/navbar.ts
  src/app/module/dialog/Accept-invitation-dialog/accept-invitation.ts
  src/app/module/dialog/Change -value/change-value.html
  src/app/module/dialog/Group-creation-dialog/group-creation.html
  src/app/pages/Connection/connection.ts
  src/app/pages/Friends/Friend-list/friend-list.html
  src/app/pages/Friends/Friend-list/friend-list.scss
  src/app/pages/Friends/Friend-list/friend-list.ts
  src/app/pages/Friends/Friend-requests/friend-request.html
  src/app/pages/Friends/Friend-requests/friend-request.scss
  src/app/pages/Friends/Friend-requests/friend-request.ts
  src/app/pages/Main_View/group_info/group_info.html
  src/app/pages/Main_View/group_info/group_info.scss
  src/app/pages/Main_View/group_info/group_info.ts
  src/app/pages/Main_View/group_list/group_list.ts
  src/app/pages/Registration/UserService.ts
  src/app/pages/Registration/registration.html
  src/app/pages/Registration/registration.ts
  src/scss/styles.scss
Labels: bug

#43 Typo correction
  src/app/pages/Friends/Friend-list/friend-list.html
  src/app/pages/Friends/Friend-list/friend-list.scss
  src/app/pages/Friends/Friend-list/friend-list.ts
  src/app/pages/User/profile/profile.html
  src/app/pages/User/profile/public/public.html
  src/app/pages/User/profile/public/public.scss
  src/app/pages/User/profile/public/public.ts
Labels: bug, enhancement

#45 Better design
  src/app/pages/EventSuggestions/event_suggestions.html
  src/app/pages/EventSuggestions/event_suggestions.scss
Labels: enhancement

#44 User role now displayed in group info
  src/app/pages/Main_View/group_info/group_info.html
  src/app/pages/Main_View/group_info/group_info.ts
Labels: bug
